WHENEVER SQLERROR EXIT SQL.SQLCODE;

ALTER SESSION SET CONTAINER = FREEPDB1;

DECLARE
  v_count NUMBER := 0;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM dba_users
   WHERE username = 'UMAI_APP';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER umai_app IDENTIFIED BY "ChangeMe123"';
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'GRANT CREATE SESSION TO umai_app';
  EXECUTE IMMEDIATE 'GRANT CREATE TABLE TO umai_app';
  EXECUTE IMMEDIATE 'GRANT CREATE SEQUENCE TO umai_app';
  EXECUTE IMMEDIATE 'GRANT CREATE VIEW TO umai_app';
  EXECUTE IMMEDIATE 'GRANT CREATE TRIGGER TO umai_app';
  EXECUTE IMMEDIATE 'GRANT CREATE PROCEDURE TO umai_app';
  EXECUTE IMMEDIATE 'GRANT UNLIMITED TABLESPACE TO umai_app';
END;
/

EXIT;
